### ISSUE TITLE
Compiler: mvn build broken

### ISSUE THREAD

**Issue by ghost** [CrispOSS/jabsc#18]
Line 74: 

 try ( final BufferedReader reader = Files.newBufferedReader(source)) {

has one missing argument of type CharSet in Files.newBufferedReader. 

Suggestion: add system default CharSet, or otherwise create class CompilerConstants with a public final static field DEFAULT_CHARSET = .... and use that one.

**Comment by ghost** [comment]
Correction: Charset ( java.nio ) instead of CharSet

**Comment by ghost** [comment]
Problem was specific to an early Java 8 build for Linux only.

**Comment by nobeh** [comment]
I'd recommend using at least Java 1.8.0u45.

**Comment by ghost** [comment]
Yep. Discovered that just on my own costs :-D

*Fortuna audaces adiuvat - hos solos ? *
